Repository uber-workflow/probot-app-usync, pull requests merged in 2019-09, with the labels that each got.

#50 Fix detection of imported PR with forks
  lib/index.js
Labels: bugfix

#51 Release v2.1.1
  package.json
Labels: release

#52 Release v2.1.2
  package.json
Labels: release

#53 Fix graphql returning null for forked repos
  lib/github.js
Labels: bugfix

#54 Release v2.1.3
  package.json
Labels: release

#55 Make error messages more helpful
  lib/lang.js
Labels: bugfix

#56 Release v2.1.4
  package.json
Labels: release

#57 Release v2.1.5
  package.json
Labels: release

#58 Ensure PRs are up-to-date and have passing checks
  .prettierrc.json
  lib/github.js
  lib/index.js
  lib/lang.js
Labels: feature

#59 Release v2.2.0
  package.json
Labels: release
